services:
  agent-zero-base:
    build:
      context: ../../
      dockerfile: ./docker/base/Dockerfile
    image: agent-zero-base:local

  agent-zero:
    depends_on:
      - agent-zero-base
    build:
      context: ../../
      dockerfile: ./docker/run/Dockerfile
    container_name: agent-zero
    restart: unless-stopped
    ports:
      - "50080:80"